# Generated by Django 3.0.8 on 2022-07-17 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_remove_to_do_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
